import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  Copy,
  Check,
  Loader2,
  Save,
  Mail,
  Maximize2,
} from 'lucide-react';
import { toast } from 'sonner';
import { JobApplication, GeneratedEmail } from '../../types/job';
import { useUserProfile } from '../../hooks/useUserProfile';
import { generateCoverLetter, generateFollowUp } from '../../lib/aiEmailGenerator';
import { FocusModeEditor } from './FocusModeEditor';

interface EmailGeneratorProps {
  job: JobApplication;
  type: 'cover_letter' | 'follow_up';
  onSave?: (email: GeneratedEmail) => Promise<void>;
  autoGenerate?: boolean;
  onGenerationComplete?: () => void;
  onContentGenerated?: (content: string) => void;
  hideUI?: boolean;
}

export const EmailGenerator = ({ job, type, onSave, autoGenerate = false, onGenerationComplete, onContentGenerated, hideUI = false }: EmailGeneratorProps) => {
  const { profile, loading: profileLoading } = useUserProfile();
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editedContent, setEditedContent] = useState('');
  const [showFocusMode, setShowFocusMode] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const title = type === 'cover_letter' ? 'Cover Letter' : 'Follow-Up Email';
  const icon = type === 'cover_letter' ? Mail : Sparkles;
  const Icon = icon;

  const handleGenerate = useCallback(async () => {
    if (!profile) {
      toast.error('Please complete your profile first to generate personalized emails');
      return;
    }

    setIsGenerating(true);
    setEditMode(false);
    
    try {
      const result = type === 'cover_letter'
        ? await generateCoverLetter(job, profile)
        : await generateFollowUp(job, profile);

      if (result.error) {
        toast.error(result.errorMessage || 'Failed to generate email');
        return;
      }

      setGeneratedContent(result.content);
      setEditedContent(result.content);
      onContentGenerated?.(result.content);
      toast.success(`${title} generated successfully!`);
      onGenerationComplete?.();
    } catch (error) {
      console.error('Error generating email:', error);
      toast.error('An error occurred while generating the email');
      onGenerationComplete?.();
    } finally {
      setIsGenerating(false);
    }
  }, [job, profile, type, title, onGenerationComplete]);

  // Auto-generate on mount if autoGenerate is true (runs even when hideUI is true)
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated && profile && !profileLoading) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
  }, [autoGenerate, hasAutoGenerated, profile, profileLoading, handleGenerate]);

  const handleCopy = async () => {
    const contentToCopy = editMode ? editedContent : generatedContent;
    
    try {
      await navigator.clipboard.writeText(contentToCopy);
      setIsCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setIsCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy to clipboard');
    }
  };

  const handleSave = async () => {
    if (!onSave) return;
    
    const contentToSave = editMode ? editedContent : generatedContent;
    
    if (!contentToSave) {
      toast.error('No content to save');
      return;
    }

    setIsSaving(true);
    
    try {
      const newEmail: GeneratedEmail = {
        id: crypto.randomUUID(),
        type,
        content: contentToSave,
        createdAt: new Date().toISOString(),
      };

      await onSave(newEmail);
      toast.success('Email saved to history!');
      setEditMode(false);
    } catch (error) {
      console.error('Error saving email:', error);
      toast.error('Failed to save email');
    } finally {
      setIsSaving(false);
    }
  };

  const handleSaveFromFocusMode = async (content: string) => {
    setEditedContent(content);
    setGeneratedContent(content);
    setEditMode(false);
    
    if (onSave) {
      const newEmail: GeneratedEmail = {
        id: crypto.randomUUID(),
        type,
        content,
        createdAt: new Date().toISOString(),
      };
      await onSave(newEmail);
    }
  };

  // If hideUI is true, don't render UI - just handle generation in background
  if (hideUI) {
    return null;
  }

  return (
    <>
      <div className="space-y-6">
        {/* Minimal Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
            <div className="p-3 rounded-xl bg-gradient-to-br from-purple-500 to-indigo-500 shadow-sm">
              <Icon className="w-6 h-6 text-white" />
          </div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white">
              {title}
            </h3>
        </div>

        <button
          onClick={handleGenerate}
          disabled={isGenerating || profileLoading}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-semibold hover:from-purple-700 hover:to-indigo-700 shadow-md hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isGenerating ? (
            <>
                <Loader2 className="w-5 h-5 animate-spin" />
              <span>Generating...</span>
            </>
          ) : (
            <>
                <Sparkles className="w-5 h-5" />
              <span>Generate</span>
            </>
          )}
        </button>
      </div>

      {/* Generated Content Area */}
      <AnimatePresence mode="wait">
        {generatedContent ? (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
              className="space-y-4"
          >
            {/* Content Display/Edit */}
            <div className="relative">
              {editMode ? (
                <textarea
                  value={editedContent}
                  onChange={(e) => setEditedContent(e.target.value)}
                    className="w-full min-h-[400px] p-6 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:border-purple-500 dark:focus:border-purple-400 focus:ring-2 focus:ring-purple-500/20 outline-none transition-all resize-none text-base leading-relaxed shadow-sm"
                />
              ) : (
                  <div className="p-6 rounded-xl bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 shadow-sm">
                    <pre className="whitespace-pre-wrap text-base text-gray-900 dark:text-gray-100 font-sans leading-relaxed">
                    {generatedContent}
                  </pre>
                </div>
              )}
            </div>

            {/* Action Buttons */}
              <div className="flex items-center gap-3 flex-wrap">
                <button
                  onClick={() => setShowFocusMode(true)}
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-medium hover:from-purple-700 hover:to-indigo-700 shadow-sm hover:shadow-md transition-all"
                >
                  <Maximize2 className="w-4 h-4" />
                  <span>Open in Focus Mode</span>
                </button>

              <button
                onClick={handleCopy}
                  className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 shadow-sm hover:shadow transition-colors"
              >
                {isCopied ? (
                  <>
                    <Check className="w-4 h-4 text-green-600" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    <span>Copy</span>
                  </>
                )}
              </button>

              {onSave && (
                <button
                  onClick={handleSave}
                  disabled={isSaving || !generatedContent}
                    className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 shadow-sm hover:shadow transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isSaving ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      <span>Saving...</span>
                    </>
                  ) : (
                    <>
                      <Save className="w-4 h-4" />
                      <span>Save to History</span>
                    </>
                  )}
                </button>
              )}
            </div>
          </motion.div>
        ) : (
            <div className="p-16 rounded-xl bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-900 border border-gray-200 dark:border-gray-700 text-center">
              <div className="inline-flex p-4 rounded-full bg-gradient-to-br from-purple-500 to-indigo-500 mb-4">
                <Sparkles className="w-8 h-8 text-white" />
              </div>
              <p className="text-lg font-medium text-gray-700 dark:text-gray-300">
                Ready to generate your {title.toLowerCase()}
            </p>
          </div>
        )}
      </AnimatePresence>
                    </div>

      {/* Focus Mode Editor */}
      <FocusModeEditor
        isOpen={showFocusMode}
        onClose={() => setShowFocusMode(false)}
        initialContent={editMode ? editedContent : generatedContent}
        documentType={type}
        title={title}
        onSave={handleSaveFromFocusMode}
      />
    </>
  );
};

