/**
 * Premium ATS Analysis Types
 * TypeScript definitions for the premium analysis structure
 */

export interface PremiumATSAnalysis {
  // Metadata
  id: string;
  userId: string;
  jobTitle: string;
  company: string;
  location?: string;
  jobUrl?: string;
  date: string;
  status?: 'processing' | 'completed' | 'failed';
  type: 'premium';
  
  // Source data (for CV Rewrite feature)
  cvText?: string;
  jobDescription?: string;
  
  // For backward compatibility and queries
  matchScore: number; // Same as match_scores.overall_score
  categoryScores: {
    skills: number;
    experience: number;
    education: number;
    industryFit: number;
  };
  
  // Premium analysis data
  executive_summary: string;
  scoring_rationale?: string; // Detailed explanation of how the score was calculated
  job_summary: JobSummary;
  match_scores: MatchScores;
  match_breakdown: MatchBreakdown;
  top_strengths: Strength[];
  top_gaps: Gap[];
  cv_fixes: CVFixes;
  cv_rewrite?: CVRewrite; // Optional, generated on-demand
  cv_rewrite_generated_at?: string; // ISO timestamp when CV was manually generated by user
  action_plan_48h: ActionPlan48H;
  learning_path: LearningPath;
  opportunity_fit: OpportunityFit;
}

export interface JobSummary {
  role: string;
  mission: string;
  key_responsibilities: string[];
  core_requirements: string[];
  hidden_expectations: string[];
}

export interface MatchScores {
  overall_score: number; // 0-100
  category: 'Weak' | 'Medium' | 'Strong' | 'Excellent';
  skills_score: number; // 0-100
  experience_score: number; // 0-100
  education_score: number; // 0-100
  industry_fit_score: number; // 0-100
  ats_keywords_score: number; // 0-100
}

export interface MatchBreakdown {
  skills: CategoryBreakdown;
  experience: CategoryBreakdown;
  education: CategoryBreakdown;
  industry: CategoryBreakdown;
  keywords: KeywordsBreakdown;
}

export interface CategoryBreakdown {
  matched: string[];
  missing: string[];
  explanations: string; // Now required for all categories - detailed explanation of the score
}

export interface KeywordsBreakdown {
  found: string[];
  missing: string[];
  priority_missing: string[];
}

export interface Strength {
  name: string;
  score: number; // 0-100
  example_from_resume: string;
  why_it_matters: string;
}

export interface Gap {
  name: string;
  severity: 'Low' | 'Medium' | 'High';
  why_it_matters: string;
  how_to_fix: string;
}

export interface CVFixes {
  high_impact_bullets_to_add: string[];
  bullets_to_rewrite: string[];
  keywords_to_insert: string[];
  sections_to_reorder: string[];
  estimated_score_gain: number;
}

export interface ActionPlan48H {
  cv_edits: string[];
  portfolio_items: string[];
  linkedin_updates: string[];
  message_to_recruiter: string;
  job_specific_positioning: string;
}

export interface LearningPath {
  one_sentence_plan: string;
  resources: LearningResource[];
}

export interface LearningResource {
  name: string;
  type: 'video' | 'course' | 'article' | 'documentation';
  link: string;
  why_useful: string;
}

export interface OpportunityFit {
  why_you_will_succeed: string[];
  risks: string[];
  mitigation: string[];
}

export interface CVRewrite {
  analysis: {
    strengths: string[];
    gaps: string[];
    recommended_keywords: string[];
    positioning_strategy: string;
    experience_relevance: string[];
  };
  initial_cv: string;
  cv_templates: {
    harvard: string;
    tech_minimalist: string;
    notion: string;
    apple: string;
    consulting: string;
    ats_boost: string;
  };
  internal_prompt_used: string;
  // NOUVEAU: Structure JSON complète et robuste pour parsing fiable
  structured_data?: {
    personalInfo: {
      name?: string;
      firstName?: string;
      lastName?: string;
      email?: string;
      phone?: string;
      location?: string;
      linkedin?: string;
      title?: string;
      jobTitle?: string;
    };
    summary: string;
    experiences: Array<{
      id: string;
      title: string;
      company: string;
      client?: string; // Pour projets sous une même entreprise
      startDate: string;
      endDate: string;
      duration?: string; // Ex: "38 months"
      location?: string;
      bullets: string[]; // TOUS les bullets, jamais de perte
    }>;
    educations: Array<{
      id: string;
      degree: string;
      institution: string;
      startDate?: string;
      endDate?: string;
      year?: string;
      gpa?: string;
      honors?: string;
      details?: string;
    }>;
    skills: string[];
    languages: Array<{
      name: string;
      level: string; // Native, Fluent, Intermediate, Basic
    }>;
    certifications: Array<{
      name: string;
      issuer?: string;
      date?: string;
      year?: string;
      credentialId?: string;
      details?: string;
    }>;
    hobbies?: string[];
  };
  validation?: {
    original_experiences_count: number;
    rewritten_experiences_count: number;
    original_educations_count: number;
    rewritten_educations_count: number;
    match: boolean;
  };
}

// Helper type for navigation
export interface NavSection {
  id: string;
  label: string;
  count?: number;
}

